server:
  port: 9000

logging:
  level:
    org.springframework.security: debug

jwt:
  key:
    public: classpath:app.pub
    private: classpath:app.key
    id: serverkey
spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
